### ISSUE TITLE
The process cannot access the file in v 1.6.0

### ISSUE THREAD

**Issue by nikryden** [i-e-b/DiskQueue#19]
Hi 
I am playing around with this project to see if I can use this in my application. I need a thread safe and persistent way to queue data.

The problem i have now is that I am not able to catch the error below it's seems random, I am probably using the library wrong, so any pointer is appreciated.

**The error:**
```
Add Test 144 thrd: 9
Add Test 145 thrd: 9
Add Test 146 thrd: 9
Read: 138 Test 138 thrd: 9  thrd: 10
Read: 139 Test 139 thrd: 9  thrd: 10
Read: 140 Test 140 thrd: 9  thrd: 10
Read: 141 Test 141 thrd: 9  thrd: 10
Read: 142 Test 142 thrd: 9  thrd: 10
Read: 143 Test 143 thrd: 9  thrd: 10
System.IO.IOException: The process cannot access the file 'C:\Playground\TestDiskQueue\TestDiskQueue\bin\Debug\net6.0\testqueue\transaction.log' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at DiskQueue.Implementation.StandardFileDriver.OpenTransactionLog(String path, Int32 bufferLength)
   at DiskQueue.Implementation.PersistentQueueImpl.WaitForTransactionLog(Byte[] transactionBuffer)
Read: 144 Test 144 thrd: 9  thrd: 10
Read: 144 Test 144 thrd: 9  thrd: 10
Read: 145 Test 145 thrd: 9  thrd: 10
Read: 146 Test 146 thrd: 9  thrd: 10
Add Test 147 thrd: 9
Add Test 148 thrd: 9
```
**The code:**

```C#
using DiskQueue;

namespace TestDiskQueue
{
    public class RunTest : IDisposable
    {
        public static bool Pause { get; set; }
        private static IPersistentQueue<Test>? _persistentQueue = PersistentQueue.WaitFor<Test>(@".\testque", TimeSpan.FromSeconds(30));
        private bool disposedValue;

        public RunTest()
        {
        }

        public void Run()
        {
            var ran = new Random();

            var t1 = new Thread(() =>
            {
                var count = 0;
                while (true)
                {
                    if (ran.Next(0, 2000) > 1000 && !Pause)
                    {
                        var ts = new Test(++count, $"Test {count} thrd: {Thread.CurrentThread.ManagedThreadId}");
                        Console.WriteLine($"Add {ts.Name}");
                        try
                        {
                            using (var session = _persistentQueue?.OpenSession())
                            {
                                session?.Enqueue(ts);
                                session?.Flush();
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                        }
                    }
                    Thread.Sleep(10);
                }
            });

            var t2 = new Thread(() =>
            {
                while (true)
                {
                    using (var session = _persistentQueue?.OpenSession())
                    {
                        Test? data;
                        try
                        {
                            Pause = true;
                            while ((data = session?.Dequeue()) != null)
                            {
                                Console.WriteLine($"Read: {data.Id} {data.Name}  thrd: {Thread.CurrentThread.ManagedThreadId}");
                                session?.Flush();
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                            continue;
                        }
                        finally
                        {
                            Pause = false;
                            Thread.Sleep(500);
                        }
                    }
                }
            });

            t1.IsBackground = true;
            t2.IsBackground = true;
            t1.Start();
            t2.Start();
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    _persistentQueue?.Dispose();
                }

                disposedValue = true;
            }
        }

        public void Dispose()
        {
            // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }

    [Serializable]
    public record Test(int Id, string Name) { }
}
````

**Comment by i-e-b** [comment]
Hi.

I hope DiskQueue works for you.

The issue is using `using (var session = _persistentQueue?.OpenSession())` in multiple threads, sharing a single `PersistentQueue`. This call doesn't wait for availability, and will throw an exception when another thread is using the queue.

Instead, use
```
using (var queue = PersistentQueue.WaitFor<Test>(@".\testque", TimeSpan.FromSeconds(30)))
using (var session = queue.OpenSession()) {
    . . . 
}
```

Inside each thread. This will capture and release the queue separately in each thread.

**Comment by nikryden** [comment]
Hi thanks for fast answer.

I have tried that but then I get:
```
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at DiskQueue.Implementation.FileStreamWrapper.ReadInt32()
   at DiskQueue.Implementation.PersistentQueueImpl.<ReadMetaState>b__85_0(IFileStream stream)
   at DiskQueue.Implementation.StandardFileDriver.<>c__DisplayClass18_0.<AtomicRead>b__0(FileStream fileStream)
   at DiskQueue.Implementation.StandardFileDriver.AtomicReadInternal(String path, Action`1 action)
   at DiskQueue.Implementation.StandardFileDriver.AtomicRead(String path, Action`1 action)
Atomic read failed: System.IO.EndOfStreamException: Attempted to read past the end of the stream.
```
have tested different maxWait, DefaultSettings and removed the testqueue folder. 


```C#
using DiskQueue;

namespace TestDiskQueue
{
    public class RunTest
    {
        public static bool Pause { get; set; }

        public RunTest()
        {
            //PersistentQueue.DefaultSettings.ParanoidFlushing = true;
            //PersistentQueue.DefaultSettings.TrimTransactionLogOnDispose = true;
            //PersistentQueue.DefaultSettings.AllowTruncatedEntries = true;
        }

        public void Run()
        {
            var ran = new Random();

            var t1 = new Thread(() =>
            {
                var count = 0;
                while (true)
                {
                    if (ran.Next(0, 2000) > 1000 && !Pause)
                    {
                        var ts = new Test(++count, $"Test {count} thrd: {Thread.CurrentThread.ManagedThreadId}");
                        Console.WriteLine($"Add {ts.Name}");
                        try
                        {
                            using (var queue = PersistentQueue.WaitFor<Test>(@".\testqueue", TimeSpan.FromSeconds(30)))
                            using (var session = queue?.OpenSession())
                            {
                                session?.Enqueue(ts);
                                session?.Flush();
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                        }
                    }
                    Thread.Sleep(100);
                }
            });

            var t2 = new Thread(() =>
            {
                while (true)
                {
                    using (var queue = PersistentQueue.WaitFor<Test>(@".\testqueue", TimeSpan.FromSeconds(30)))
                    using (var session = queue?.OpenSession())
                    {
                        Test? data;
                        try
                        {
                            Pause = true;
                            while ((data = session?.Dequeue()) != null)
                            {
                                Console.WriteLine($"Read: {data.Id} {data.Name}  thrd: {Thread.CurrentThread.ManagedThreadId}");
                                session?.Flush();
                            }
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine(ex);
                            continue;
                        }
                        finally
                        {
                            Pause = false;
                            Thread.Sleep(500);
                        }
                    }
                }
            });

            t1.IsBackground = true;
            t2.IsBackground = true;
            t1.Start();
            t2.Start();
        }
    }

    [Serializable]
    public record Test(int Id, string Name)
    {
    }
}
```

**Comment by i-e-b** [comment]
That can often be due to disk driver issues. DiskQueue should retry when it gets that exception  -- based on `DiskQueue.Implementation.StandardFileDriver.RetryLimit`, which is 10 times.

Do you get the `Attempted to read past the end of the stream` multiple times, or is it once then it works?

**Comment by nikryden** [comment]
It never works I get the same error in both thread t1 and t2. 

This message never happens when i put PersistentQueue.WaitFor<Test>static outside like in my first code example, but then i get ``` System.IO.IOException: The process cannot access the file ``` and that seems randomly.

I provide my test project if it will help

[TestDiskQueue.zip](https://github.com/i-e-b/DiskQueue/files/10130984/TestDiskQueue.zip)

**Comment by i-e-b** [comment]
With that code as-is, it runs with the occasional `System.TimeoutException` error.

If I put the two `using`s inside the `try`  of  `t2`, it zooms along with no errors.
[TestDiskQueue_modified.zip](https://github.com/i-e-b/DiskQueue/files/10131252/TestDiskQueue_modified.zip)

Other users have reported similar errors, but only on specific machines. I think one traced it down to a faulty SSD drive.
Sorry that doesn't help in this case.

If I get time, I will try to make a memory-mapped file driver, and see if that helps.

**Comment by nikryden** [comment]
Thanks it almost work and it make it easier to debug :)
I still get the error if i do a Dequeue and the queue folder not exists. 
But if I do Equeue first it works and after that Dequeue also work correctly.

**Comment by nikryden** [comment]
One thing I also notices is (I don't now if its a bug or a feature) that PersistentQueue not propagate the errors so it can be catch with a try block when it have done the 10 tries

**Comment by nikryden** [comment]
May I come with a suggestion
 in DiskQueue.Implementation/StandardFileDriver.cs method AtomicRead and AtomicWrite add a 
``` if (i >= RetryLimit) throw; ```
or throw something like ```if (i >= RetryLimit) throw new DiskQueueMaxTryException("Failed to read file stream") ``` so there is possible to act on this error. 

eg.
```C#
  public void AtomicRead(string path, Action<IFileStream> action)
        {
            for (int i = 0; i < RetryLimit + 1; i++)
            {
                try
                {
                    AtomicReadInternal(path, fileStream =>
                    {
                        var wrapper = new FileStreamWrapper(fileStream);
                        action(wrapper);
                    });
                    return;
                }
                catch (UnrecoverableException)
                {
                    throw;
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Atomic read failed: {ex}");
                    if (i >= RetryLimit) throw;
                    Thread.Sleep(i * 100);
                }
            }
        }
````

**Comment by i-e-b** [comment]
That makes sense. I will add it.

**Comment by i-e-b** [comment]
I've uploaded version 1.6.2 to NuGet, which has the change above and a few other small tweaks.
https://www.nuget.org/packages/DiskQueue/1.6.2

I can't see anywhere obvious that could be causing these issues.
If I get time, I will re-write the core of this and release a version 2.

(Just after uploading 1.6.1, I found a very weird corner case. I doubt it's what's causing this issue, but 1.6.2 removes it)

**Comment by nikryden** [comment]
Thanks Ian, I appreciate that you taking the time to fix these things. 
I will test the version 1.6.2 tomorrow to see if I it's fix it :).

**Comment by nikryden** [comment]
The 1.6.2 seems to fix the above issues for me. I close this issue

**Comment by i-e-b** [comment]
Thanks for letting me know.
